#阿里云服务器
server:
  port: 12345
  tomcat:
    uri-encoding: utf-8

eureka:
  client:
    service-url:
      defaultZone: http://www.vivtoum.tech:1001/eureka/                    #部署信息（注册中心地址）
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles: single
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.vivtoum.tech:3306/springbootdemo?useSSL=false
    username: '{cipher}AQBWKljmfedMRv0k6Mf/XFBR2eGfmFdywzjSkC23vVROVQi06mSx4HmUQ9oTuO5ndj1FW3RrRl2/W1xVJb4fcbMYWCst7L27JmyIdvZ5NXTY/07cmcri5w9xcLs4CVLN09EphKPzgryXPlhQQP48uKJcdtxIO8dqcMjn7C3cKP5tpHhqURHvCmKD0SBTubkpcdf7BG6RvBQoVYoNJS9Zv1HVaZ+GWfHkhSRq6k1o/5ANfNan94XD+UE7wUKNnvNbROEwpSUZv1aQXocPMAquqKRUVusNDzbZymEPYmZsZRMqlqM5viAJmJMRhfF6/lK20WZEjSzGnnDK70LhKji/Q+Q7V/dM+Snk2JwSuLRLQ31tA/GBvivVmS4xasjGmS+xiuA='
    password: '{cipher}AQCExPOL2gBjU3r2DNsy+82n1Cju2FDFfA8Oezgn1uUIr+BuY2HozZ1a3Ko57Pba9HsovfBCp6CmhM8EirqDT6pkADo+jIhjW5pS/GMnmOIeHi6tBxRGkXFZL9XxbPqKdOH3NUKXB4eHTKcaWmP5793OJULa/mZ2m4bVzOXRIkf4WPpYgMnK3Bd5PNC2gbcQc77XwovEqIbj6icwBQVc34epGPFsj1g0atECoFKoy3F1jq+Xr8eQS+79B7LGym8WHF7bpm4C4wCVrFIRbwO6PM5Xdt055aBMrzvqnz4tg9H8hSqs9c7R2mBlQ/20S5lLJeo43EIemH8lO7zE849wKs4989AYyvsqdnldciEAFoc+4fiaE5unOcE7XzlkOv2tsc4='
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: www.vivtoum.tech                                #部署信息（Redis主机地址）
    port: 6379                                            #部署信息（Redis访问端口）
    password: '{cipher}AQCK/iz3ke6T9EiUZKaU38NzRgSHApPYaSyMXX2gBRkOl3+P73lQv/3xWLckpXqnU6rm2btDc5YOdxt2/IitIH9Yu5YeOxzfDqrfO+KZfNrS6IwbD9bPdX7yd1HFPBthabjKrvBdxa33GCmjtLYNqgclIisNIaDbJozycIziWZ+B2dpb9EHgOY8RdPTw7/gEAQQMcRVdhSuICojIDr++XEHuX+smq4WV99+FTFZYo3/1A67QTBtDkdlC9lHoNJe5+KhwNBolOTsL4OHYiwJZJBtx4hHaf7gjRbLKlt5jGjc2I1YR/pBpkso0RyrcHBuahIS1l7AcWHeKzqN/XyTQhaPrpJAk8aF9MLMM4OAAaNDeK2jIEtU5VMOlDC/6d704bks='                               #部署信息（Redis认证密码）

blog-svc:
  url: http://localhost:${server.port}