server:
  port: 2102
spring:
  profiles: dev2
  application:
    name: client1
  datasource:
    url: jdbc:mysql://39.104.49.60:3306/springbootdemo?useSSL=false
    #    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=false

    username: '{cipher}AQCQgEqOiM2/zQTs5P5/yO85CGN8V6w2FumtMo1rvtXWMsd6+FV6S7fpdxOk3QMDKfhkbB0mYi7r7DJqaaeKQWiwtqP0lgP+tK5nPDeplZ4jcK8A4aOGbjGda7NM7LXkQ9m0xN7+8c2ikJF1E9CO7BAaNP3ER3QxaCy/4JHhTxWk+gSxQ5EGd5kyDskk6Q5LDArbDbIIgvpbiVm2TnayoFh/r30jMQ8u4OlEHvWeup6gEmlGPrX1n4x/N+YvVYRICmXIC57gG+qGbqeMcO3sYyBUYVuBEWlITtjqdHA8fpjEhTq3Ngd5JGCMx8vbCnLQoSNMn/lmovmEIx0ym0wOsTxfYqiZYe/otMCFV+We3NicW0vcVFs2vDRHann304J89iQ='
    password: '{cipher}AQB3CpTWAI5N4/xfI6IgGSyEKpUyVdniC3VXUddyIdR0a+4hCOm7bHlEwUhsJMOz4g108nedv6JFs1TRRm5rdIfzd7DfFwRt7vqIL74HAnPzUfQvxKFwQ0kgUhiqrYPD+c1qfp3Y8GW1oir9cEsbFY+OMQw3dXcsP8F0ZsrEmHy+f615x4Sqj7NuZ1jhJvlz0l4HYcXM5g0hb9LAq/zc8wIUSsZRjnfFjaF4Jh6NqCFmSVBhPv7URY7iFv6rxkbVpfkEAZ+pWbE3zbuGB7It3aWQrKbsRStkfVJo6pSD2K4i4SsU32lLlVFqLtHdpEeoHpYuPK2RqM44YOmaRjHUgWo6jLoccMjzdWxqx1R9hf+aIKvyBUeec2t4vfkOzOusFps='
    tomcat:
      max-active: 100
      max-idle: 200
      initial-size: 20
      driver-class-name: com.mysql.jdbc.Driver
    #    type: com.zaxxer.hikari.HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://svc1:1001/eureka/,http://svc2:1002/eureka/,http://svc3:1003/eureka/
#test: '{cipher}AQB2xJvbko/P5BA9FRffk384b4bowV5HtVgrekKKkY9PO5WbJT/s94+b8xFhdOhuzrSLoHkYnLZLIvuYKpD4VyZLoTphu02n3Ho12uGTNrLvy4NL+yApwmkownvMXwLuEV58Zd6S0pi6rcNs1yM4WaN2Oo+ZV+6ghLg7J8fd1b/iZj3uHq8/vn+6UOupgHpa7a16DzktHJ9w6rIZYwWCFtTEqyWaRENG3dSLAJtyFJe+/9z/oX5DdS8Tj4iAk474edd4uQgxLRc+/d8uohjxbPaMCRHrNwfOyfKBmQHuSRWxUob5u0FMlX024BUrAjTFrGB3pBKs5xcgBwjEki2B+r0g+yAoQe+1wh0z2WTnpuZdCrdtOu8SGvWdMt2MZ/coqPM='
test: test-2
