spring:
  application:
    name: eureka-fegin
server:
  port: 2101
eureka:
  client:
    serviceUrl:
      defaultZone: http://svc1:1001/eureka/,http://svc2:1002/eureka/,http://svc3:1003/eureka/

test: '{cipher}AQBRfxgAlhLeuw/Zg0LWvtaNlFFrcTknAvX9mzeMStZ3XNDuGYERXG4v/S+pkbGd+3ARQxIN+juYzyTwIURvrOlah0Coe2SfmMF1aa1MRMpazC/7hgTpThy89KgTXCInhw3qvesba2vBjjH3ZMBuxZiB8jS/ain3XRx31nDy5V/wFTINJxuSAt6e51f6ekCQiZ0AjdVugDuhs5ovhH8bBGcjKzBCjDQ4TN/6EZm4pThzmAhuGNf7CuvtZLuidc2VidPIabi+C104HUI1pYZWAk03O5cakyRqHhAWaXleKv2SNMZNLFAgx3NpSEGohSV3tUw+YiJV9nzAxnnaB4sTjtGfDTylzI4Ng6cNbE9gHW26z9ua9ZuK3jnHMlmseAD23V0='