spring:
  application:
    name: eureka-fegin
server:
  port: 2101
eureka:
  client:
    serviceUrl:
      defaultZone: http://svc1:1001/eureka/,http://svc2:1002/eureka/,http://svc3:1003/eureka/

test: '{cipher}AQB6Onl5Or/mm30MTaj/x+GbL820fEWLni2J482bIPJaNRihHbaNEDmiEFLx2Rz77Yhpy3VMTNfCZZTMdz6NeuE7//QVuwsXj7ko1VpPG/MQtC7qfSpdDM2JWQkWAlDJhs1HsxQcbWv27msGiB/KyixR4/NGAAu1VDI5F6aJS0tB65kGxVHec3tGpt60sy4MnhaIPl0uTmLykbz6jEHiu+lEKaGdZoONs1Q7yjhOIW4hOnMkMko3jxzTrQPS+MLRwI375I3vHhM3ABG48OKFDU+yQcJO6HY6ndyl9G+bRrI/ONy0+M6DGpNYZmHTZIlZAtlf5KKwxbKHnh9Mgkar0zU0RtLsKnjOJkcSrmyPu1T6MDHC6AB/BBM9bhXSKDUwNGE='