spring:
  application:
    name: eureka-client
server:
  port: 2001
eureka:
  client:
    serviceUrl:
      defaultZone: http://svc1:1001/eureka/,http://svc2:1002/eureka/,http://svc3:1003/eureka/

test: dev分支
